//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumeryProj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryChangeProductPrice
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
