//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParfumeryProj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Basket = new HashSet<Basket>();
            this.HistorySale = new HashSet<HistorySale>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<int> ManagerUserID { get; set; }
        public Nullable<int> ClientUserID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorySale> HistorySale { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
